### ISSUE TITLE
Trouble with https://web.archive.org/web/20140324020304/http://www.solv.ch/files/magazin/blw2014_nachwuchs.pdf

### ISSUE THREAD

**Issue by jrmuizel** [J-F-Liu/lopdf#29]
I get a bunch of the following:
```
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 9137).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 9383 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 24036).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 24282 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 38935).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 39181 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 53834).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 54080 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 68733).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 68979 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 83632).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 83878 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 98531).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 98777 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 113430).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 113676 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 164220).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 164466 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 215010).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 215256 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 265755).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 265914 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 266025).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 266184 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 266970).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 267129 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 275356).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 275515 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 279461).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 279620 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 310100).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 310259 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 310855).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 311014 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 357054).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 357213 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 363298).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 363457 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 369716).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 369875 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 374713).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 374872 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 375742).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 375901 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 379986).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 380145 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 389773).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 389932 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 391382).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 391541 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 404469).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 404628 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 446244).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 446403 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 490353).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 490512 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 538405).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 538564 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 538913).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 539072 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 545760).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 545919 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 547091).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 547250 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 588499).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 588658 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 634527).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 634686 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 638297).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 638456 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 721012).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 721171 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 721633).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 721792 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 805803).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 805962 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 808239).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 808398 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 808676).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 808835 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 820750).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 820909 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 846137).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 846296 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 849787).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 849946 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 850280).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 850439 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 850918).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 851077 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 851558).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 851717 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 852197).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 852356 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 852675).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 852834 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 853163).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 853322 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 853657).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 853816 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 854201).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 854360 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 854680).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 854839 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 855264).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 855423 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 855774).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 855933 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 856291).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 856450 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 856873).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 857032 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 857465).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 857624 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 857948).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 858107 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 858384).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 858543 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 858902).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 859061 }") }
Custom { kind: InvalidData, error: StringError("Not a valid PDF file (read object at 859556).\nMismatch { message: \"seq endobj expect: 101, found: 115\", position: 859616 }") }
```

and then a panic at:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [70, 109, 48, 95, 48, 95, 45, 52, 95, 49, 55, 95, 70, 108, 228, 99, 104, 101, 95, 79, 98, 106, 101, 107, 116, 95, 67, 61, 48, 95, 77, 61, 50, 51, 48, 95, 89, 61, 50, 51, 48, 95, 75, 61, 48], error: Utf8Error { valid_up_to: 14, error_len: Some(1) } }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::begin_panic
             at libstd/panicking.rs:402
   5: std::panicking::try::do_call
             at libstd/panicking.rs:349
   6: std::panicking::try::do_call
             at libstd/panicking.rs:325
   7: core::ptr::drop_in_place
             at libcore/panicking.rs:72
   8: core::result::unwrap_failed
             at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:782
  10: lopdf::parser::dictionary::{{closure}}::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/lopdf-0.15.1/src/parser.rs:107
  11: core::iter::iterator::Iterator::fold::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libcore/iter/iterator.rs:1594
  12: core::iter::iterator::Iterator::try_fold
             at /Users/travis/build/rust-lang/rust/src/libcore/iter/iterator.rs:1481
  13: core::iter::iterator::Iterator::fold
             at /Users/travis/build/rust-lang/rust/src/libcore/iter/iterator.rs:1594
  14: lopdf::parser::dictionary::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/lopdf-0.15.1/src/parser.rs:105
  15: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a F>::call_once
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:252
  16: <core::result::Result<T, E>>::map
             at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:468
  17: <pom::parser::Parser<'a, I, O>>::map::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:34
  18: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  19: <pom::parser::Parser<'a, I, O>>::map::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:34
  20: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  21: <pom::parser::Parser<'a, I, O> as core::ops::bit::BitOr>::bitor::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:520
  22: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  23: <pom::parser::Parser<'a, I, O> as core::ops::arith::Sub<pom::parser::Parser<'b, I, U>>>::sub::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:469
  24: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  25: pom::parser::call::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:426
  26: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  27: <pom::parser::Parser<'a, I, O> as core::ops::arith::Add<pom::parser::Parser<'b, I, U>>>::add::{{closure}}::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:453
  28: <core::result::Result<T, E>>::and_then
             at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:621
  29: <pom::parser::Parser<'a, I, O> as core::ops::arith::Add<pom::parser::Parser<'b, I, U>>>::add::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:453
  30: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  31: <pom::parser::Parser<'a, I, O>>::repeat::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:129
  32: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  33: <pom::parser::Parser<'a, I, O> as core::ops::arith::Mul<pom::parser::Parser<'b, I, U>>>::mul::{{closure}}::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:485
  34: <core::result::Result<T, E>>::and_then
             at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:621
  35: <pom::parser::Parser<'a, I, O> as core::ops::arith::Mul<pom::parser::Parser<'b, I, U>>>::mul::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:485
  36: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  37: <pom::parser::Parser<'a, I, O> as core::ops::arith::Sub<pom::parser::Parser<'b, I, U>>>::sub::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:469
  38: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  39: <pom::parser::Parser<'a, I, O>>::map::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:34
  40: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  41: <pom::parser::Parser<'a, I, O>>::map::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:34
  42: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  43: <pom::parser::Parser<'a, I, O> as core::ops::bit::BitOr>::bitor::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:520
  44: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  45: <pom::parser::Parser<'a, I, O> as core::ops::arith::Sub<pom::parser::Parser<'b, I, U>>>::sub::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:469
  46: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  47: pom::parser::call::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:426
  48: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  49: <pom::parser::Parser<'a, I, O> as core::ops::arith::Add<pom::parser::Parser<'b, I, U>>>::add::{{closure}}::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:453
  50: <core::result::Result<T, E>>::and_then
             at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:621
  51: <pom::parser::Parser<'a, I, O> as core::ops::arith::Add<pom::parser::Parser<'b, I, U>>>::add::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:453
  52: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  53: <pom::parser::Parser<'a, I, O>>::repeat::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:129
  54: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  55: <pom::parser::Parser<'a, I, O> as core::ops::arith::Mul<pom::parser::Parser<'b, I, U>>>::mul::{{closure}}::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:485
  56: <core::result::Result<T, E>>::and_then
             at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:621
  57: <pom::parser::Parser<'a, I, O> as core::ops::arith::Mul<pom::parser::Parser<'b, I, U>>>::mul::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:485
  58: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  59: <pom::parser::Parser<'a, I, O> as core::ops::arith::Sub<pom::parser::Parser<'b, I, U>>>::sub::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:469
  60: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  61: <pom::parser::Parser<'a, I, O>>::map::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:34
  62: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  63: <pom::parser::Parser<'a, I, O> as core::ops::arith::Sub<pom::parser::Parser<'b, I, U>>>::sub::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:469
  64: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  65: <pom::parser::Parser<'a, I, O> as core::ops::arith::Sub<pom::parser::Parser<'b, I, U>>>::sub::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:469
  66: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  67: <pom::parser::Parser<'a, I, O> as core::ops::arith::Sub<pom::parser::Parser<'b, I, U>>>::sub::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:469
  68: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  69: <pom::parser::Parser<'a, I, O> as core::ops::bit::Shr<F>>::shr::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:501
  70: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  71: <pom::parser::Parser<'a, I, O>>::map::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:34
  72: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  73: <pom::parser::Parser<'a, I, O> as core::ops::bit::BitOr>::bitor::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:520
  74: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  75: <pom::parser::Parser<'a, I, O> as core::ops::bit::BitOr>::bitor::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:516
  76: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  77: <pom::parser::Parser<'a, I, O> as core::ops::arith::Sub<pom::parser::Parser<'b, I, U>>>::sub::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:469
  78: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  79: <pom::parser::Parser<'a, I, O> as core::ops::arith::Add<pom::parser::Parser<'b, I, U>>>::add::{{closure}}::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:453
  80: <core::result::Result<T, E>>::and_then
             at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:621
  81: <pom::parser::Parser<'a, I, O> as core::ops::arith::Add<pom::parser::Parser<'b, I, U>>>::add::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:453
  82: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  83: <pom::parser::Parser<'a, I, O> as core::ops::arith::Sub<pom::parser::Parser<'b, I, U>>>::sub::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:469
  84: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  85: <pom::parser::Parser<'a, I, O> as core::ops::arith::Sub<pom::parser::Parser<'b, I, U>>>::sub::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:469
  86: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  87: <pom::parser::Parser<'a, I, O> as core::ops::arith::Sub<pom::parser::Parser<'b, I, U>>>::sub::{{closure}}
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:469
  88: <pom::parser::Parser<'a, I, O>>::parse
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/pom-1.1.0/src/parser.rs:23
  89: lopdf::reader::Reader::read_object
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/lopdf-0.15.1/src/reader.rs:139
  90: <pom::input::DataInput<'a, T> as pom::input::Input<T>>::position
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/lopdf-0.15.1/src/reader.rs:91
  91: lopdf::reader::<impl lopdf::document::Document>::load_internal
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/lopdf-0.15.1/src/reader.rs:38
  92: lopdf::reader::<impl lopdf::document::Document>::load
             at /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/lopdf-0.15.1/src/reader.rs:19
```

**Comment by J-F-Liu** [comment]
The stream length number is wrong, doest not match actual stream content.
